In [4]:
import numpy as np

np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [17]:
import numpy as np

empirical_quantiles = torch.Tensor([
    [-1.2, 0, 3.3, 6.7],
    [-2.3, 1.2, 1.3, 5]
])

y_true = torch.Tensor([
    1,1,1,1
])

tf_mat = empirical_quantiles >= y_true

In [18]:
tf_mat.sum(dim = 1)

tensor([2, 3])

In [14]:
tf_mat.sum(dim=1)

tensor([[2, 2, 4],
        [1, 3, 4]])

In [25]:
mean1 = torch.Tensor([1,2,3])
mean2 = torch.Tensor([1,2,3])
hold = torch.stack([mean1, mean2], dim = 0)
hold.mean(dim = 0)

tensor([1., 2., 3.])

In [26]:
hold.var(dim = 0)

tensor([0., 0., 0.])

In [27]:
quantiles = torch.Tensor([0.2, 0.8]).view(-1, 1)
sigs = torch.Tensor([1.1, 2.2, 3.4, 5.6])

quantiles * sigs

tensor([[0.2200, 0.4400, 0.6800, 1.1200],
        [0.8800, 1.7600, 2.7200, 4.4800]])

In [29]:
import torch.nn as nn

toh1 = torch.Tensor([1,4,3,2])
toh2 = torch.Tensor([3,4,1,2])

nn.MSELoss()(toh1, toh2)

tensor(2.)